### PR TITLE
feat: header/footer tweaks

### PR DESCRIPTION
**Pull request by jessicaschilling**
## In this PR
- Tidies header for brevity
image
- Makes tab title clearer
image
- Tidies footer, including:
     - Adding GitHub link (ref #72)
     - At desktop widths, moving all material to left to avoid a11y figure/ground problem
     image
     - At mobile widths, rearranging for better visual hierarchy
    image

_NOTE:_ There are some already-existing display issues at narrow mobile widths that we'll want to address separately.

Closes https://github.com/ipfs-shipyard/ipfs-share-files/issues/72.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@terichadbourne - CCing you on this one since I can't add you as a reviewer by default.

**Review by lidel — APPROVED** [review]
Indeed better! LGTM. 

I've added @terichadbourne to the project, reviews should work now

**Comment by jessicaschilling** [comment]
Thanks -- @lidel @terichadbourne @rafaelramalho19, please feel free to merge this once https://github.com/ipfs-shipyard/ipfs-share-files/pull/87 is approved. Thanks!

**Review by terichadbourne — APPROVED** [review]
Looks great!

**Pull request merged**
